/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicamedicasolidarista.vista;

import clinicamedicasolidarista.controlador.Controlador;
import static clinicamedicasolidarista.vista.vistaLogin.BORDER_ERROR;
import static clinicamedicasolidarista.vista.vistaLogin.BORDER_RIGHT;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import org.apache.commons.codec.digest.DigestUtils;


/**
 *
 * @author KENNETT
 */
public class CambiarPass extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form CambiarPass
     */
    public CambiarPass(Controlador control) {
        initComponents();       
        this.control=control;
        control.registrarObservador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etqUsuario = new javax.swing.JLabel();
        iconAsetaca = new javax.swing.JLabel();
        etqCodigo = new javax.swing.JLabel();
        etqContraseña = new javax.swing.JLabel();
        etqTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iconUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textCodigo = new javax.swing.JPasswordField();
        textNueva = new javax.swing.JPasswordField();
        btnGuargar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        iconContraseña = new javax.swing.JLabel();
        iconCodigo = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 400));
        setMinimumSize(new java.awt.Dimension(450, 400));
        setPreferredSize(new java.awt.Dimension(450, 400));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqUsuario.setText("Nombre de Usuario");
        jPanel1.add(etqUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        iconAsetaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/asetacaMediano.png"))); // NOI18N
        jPanel1.add(iconAsetaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 50));

        etqCodigo.setText("Codigo de Seguridad");
        jPanel1.add(etqCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        etqContraseña.setText("Nueva Contraseña");
        jPanel1.add(etqContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        etqTitulo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        etqTitulo.setText("CAMBIAR CONTRASEÑA");
        jPanel1.add(etqTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 240, 10));

        iconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/user_1.png"))); // NOI18N
        jPanel1.add(iconUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 40, 70));

        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 160, 20));
        jPanel1.add(textCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 160, 20));
        jPanel1.add(textNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 160, 20));

        btnGuargar.setText("GUARDAR");
        btnGuargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 80, -1));

        iconContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/lock (2).png"))); // NOI18N
        jPanel1.add(iconContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        iconCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/qr-code (1).png"))); // NOI18N
        jPanel1.add(iconCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        panelPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/fondoBlanco.jpg"))); // NOI18N
        panelPrincipal.setText("jLabel4");
        jPanel1.add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuargarActionPerformed
       if(textCodigo.getText().equals("")){
            textCodigo.setBorder(BORDER_ERROR);
            textCodigo.setToolTipText("Digite el codigo");
        }
        else{
            textNueva.setBorder(BORDER_RIGHT);
            textNueva.setToolTipText("");}
          
             if(textNueva.getText().equals("")){
            textNueva.setBorder(BORDER_ERROR);
            textNueva.setToolTipText("Digite su nueva contraseña");
        }
        else{
            textUsuario.setBorder(BORDER_RIGHT);
            textUsuario.setToolTipText("");}
             
                if(textUsuario.getText().equals("")){
            textUsuario.setBorder(BORDER_ERROR);
            textUsuario.setToolTipText("Digite su usuario");
        }
        else{
            textUsuario.setBorder(BORDER_RIGHT);
            textUsuario.setToolTipText("");}
        
        boolean bandera=control.cambiarContrasena(textUsuario.getText(),this.textCodigo.getText(), DigestUtils.shaHex(this.textNueva.getText()));
        if(bandera==false){
     JOptionPane.showMessageDialog(this,"Debe ingresar los datos correctamente", "Mensaje de Error", //Título
    JOptionPane.ERROR_MESSAGE); 
        }else{
    /*JOptionPane.showMessageDialog(this,"Contraseña Cambiada", "Confirmado", //Título
    JOptionPane.INFORMATION_MESSAGE);*/ 
        }   
            
        /*JOptionPane.showConfirmDialog(this,"Algun dato es incorrecto");
        }else{
        JOptionPane.showConfirmDialog(this,"Contraseña cambiada");
        }*/
    }//GEN-LAST:event_btnGuargarActionPerformed

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.hide();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarPass().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuargar;
    private javax.swing.JLabel etqCodigo;
    private javax.swing.JLabel etqContraseña;
    private javax.swing.JLabel etqTitulo;
    private javax.swing.JLabel etqUsuario;
    private javax.swing.JLabel iconAsetaca;
    private javax.swing.JLabel iconCodigo;
    private javax.swing.JLabel iconContraseña;
    private javax.swing.JLabel iconUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel panelPrincipal;
    private javax.swing.JPasswordField textCodigo;
    private javax.swing.JPasswordField textNueva;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
    private Controlador control;

    @Override
    public void update(Observable model, Object o1) {
        
        
        if(model.equals("cambiar")){
        this.textCodigo.setText("");
        this.textNueva.setText("");
        this.textUsuario.setText("");
        }

           
    }

    public static Border BORDER_ERROR = BorderFactory.createLineBorder(Color.red);
    public static Border BORDER_NOBORDER = BorderFactory.createLineBorder(Color.red);
   
    public static Border BORDER_RIGHT = BorderFactory.createLineBorder(Color.BLACK);
    public static Border BORDER_BORDERRIGHT = BorderFactory.createLineBorder(Color.BLACK);
}
