/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicamedicasolidarista.vista;
import java.awt.Color;
import clinicamedicasolidarista.ClinicaMedicaSolidarista;


/**
 *
 * @author Pablo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAgenda = new javax.swing.JButton();
        jButtonRegCita = new javax.swing.JButton();
        jButtonKardex = new javax.swing.JButton();
        jButtoncContactos = new javax.swing.JButton();
        jButtonParame = new javax.swing.JButton();
        jButtonRepYEst = new javax.swing.JButton();
        jButtonKardex1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(959, 570));
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonAgenda.setBackground(new java.awt.Color(8, 83, 148));
        jButtonAgenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAgenda.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgenda.setText("AGENDA");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgenda);
        jButtonAgenda.setBounds(40, 110, 540, 60);

        jButtonRegCita.setBackground(new java.awt.Color(8, 83, 148));
        jButtonRegCita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRegCita.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegCita.setText("REGISTRAR CITA");
        jButtonRegCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegCitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegCita);
        jButtonRegCita.setBounds(40, 200, 260, 60);

        jButtonKardex.setBackground(new java.awt.Color(8, 83, 148));
        jButtonKardex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKardex.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKardex.setText("ESTADISTICAS(falta)");
        getContentPane().add(jButtonKardex);
        jButtonKardex.setBounds(320, 360, 260, 60);

        jButtoncContactos.setBackground(new java.awt.Color(8, 83, 148));
        jButtoncContactos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtoncContactos.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncContactos.setText("CONTACTOS");
        getContentPane().add(jButtoncContactos);
        jButtoncContactos.setBounds(40, 360, 260, 60);

        jButtonParame.setBackground(new java.awt.Color(8, 83, 148));
        jButtonParame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonParame.setForeground(new java.awt.Color(255, 255, 255));
        jButtonParame.setText("PARAMETRIZACIÓN");
        jButtonParame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParameActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonParame);
        jButtonParame.setBounds(320, 200, 260, 60);

        jButtonRepYEst.setBackground(new java.awt.Color(8, 83, 148));
        jButtonRepYEst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRepYEst.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRepYEst.setText("REPORTES(falta)");
        jButtonRepYEst.setActionCommand("REPORTES (falta)");
        jButtonRepYEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepYEstActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRepYEst);
        jButtonRepYEst.setBounds(320, 280, 260, 60);

        jButtonKardex1.setBackground(new java.awt.Color(8, 83, 148));
        jButtonKardex1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKardex1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKardex1.setText("KÁRDEX");
        jButtonKardex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKardex1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKardex1);
        jButtonKardex1.setBounds(40, 280, 260, 60);

        jDesktopPane1.setBackground(new java.awt.Color(5, 47, 154));

        jDesktopPane2.setBackground(new java.awt.Color(5, 47, 154));
        jDesktopPane1.add(jDesktopPane2);
        jDesktopPane2.setBounds(0, 510, 960, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/E2.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(930, 0, 20, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SISTEMA DE ADMINISTRACION DE CITAS MEDICAS - MENU PRINCIPAL");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(10, 0, 480, 20);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 960, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/be21.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 520);

        jDesktopPane3.setBackground(new java.awt.Color(5, 47, 154));

        jDesktopPane4.setBackground(new java.awt.Color(5, 47, 154));
        jDesktopPane3.add(jDesktopPane4);
        jDesktopPane4.setBounds(0, 510, 960, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BIENVENIDO @USUARIO");
        jDesktopPane3.add(jLabel7);
        jLabel7.setBounds(410, 20, 160, 20);

        getContentPane().add(jDesktopPane3);
        jDesktopPane3.setBounds(0, 500, 960, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
          ClinicaMedicaSolidarista.AGENDA.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jButtonRegCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegCitaActionPerformed
        vistaSolicitudCita VSC=new vistaSolicitudCita();
        VSC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegCitaActionPerformed

    private void jButtonParameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParameActionPerformed
        SubmenuParametrizacion mp=new SubmenuParametrizacion();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonParameActionPerformed

    private void jButtonRepYEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepYEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRepYEstActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         ClinicaMedicaSolidarista.LOGIN.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButtonKardex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKardex1ActionPerformed
          ClinicaMedicaSolidarista.KARDEX.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jButtonKardex1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonKardex;
    private javax.swing.JButton jButtonKardex1;
    private javax.swing.JButton jButtonParame;
    private javax.swing.JButton jButtonRegCita;
    private javax.swing.JButton jButtonRepYEst;
    private javax.swing.JButton jButtoncContactos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
