/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicamedicasolidarista.vista;
import java.awt.Color;
import clinicamedicasolidarista.ClinicaMedicaSolidarista;


/**
 *
 * @author Pablo
 */
public class Menu1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAgenda = new javax.swing.JButton();
        jButtonKardex = new javax.swing.JButton();
        jButtoncContactos = new javax.swing.JButton();
        jButtonKardex1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        etqTitulo3 = new javax.swing.JLabel();
        etqTitulo1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(330, 520));
        setMinimumSize(new java.awt.Dimension(330, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonAgenda.setBackground(new java.awt.Color(8, 83, 148));
        jButtonAgenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAgenda.setForeground(new java.awt.Color(6, 69, 135));
        jButtonAgenda.setText("Registrar Medico");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgenda);
        jButtonAgenda.setBounds(110, 140, 260, 50);

        jButtonKardex.setBackground(new java.awt.Color(8, 83, 148));
        jButtonKardex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKardex.setForeground(new java.awt.Color(6, 69, 135));
        jButtonKardex.setText("Modificar Medico");
        getContentPane().add(jButtonKardex);
        jButtonKardex.setBounds(110, 260, 260, 50);

        jButtoncContactos.setBackground(new java.awt.Color(8, 83, 148));
        jButtoncContactos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtoncContactos.setForeground(new java.awt.Color(6, 69, 135));
        jButtoncContactos.setText("Eliminar Medico");
        jButtoncContactos.setToolTipText("");
        getContentPane().add(jButtoncContactos);
        jButtoncContactos.setBounds(110, 320, 260, 50);

        jButtonKardex1.setBackground(new java.awt.Color(8, 83, 148));
        jButtonKardex1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKardex1.setForeground(new java.awt.Color(6, 69, 135));
        jButtonKardex1.setText("Consultar Registro");
        getContentPane().add(jButtonKardex1);
        jButtonKardex1.setBounds(110, 200, 260, 50);

        jDesktopPane1.setBackground(new java.awt.Color(5, 47, 154));

        jDesktopPane2.setBackground(new java.awt.Color(5, 47, 154));
        jDesktopPane1.add(jDesktopPane2);
        jDesktopPane2.setBounds(0, 510, 960, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/E2_1.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(480, 0, 20, 20);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 960, 20);

        jDesktopPane3.setBackground(new java.awt.Color(5, 47, 154));

        jDesktopPane4.setBackground(new java.awt.Color(5, 47, 154));
        jDesktopPane3.add(jDesktopPane4);
        jDesktopPane4.setBounds(0, 510, 960, 20);

        getContentPane().add(jDesktopPane3);
        jDesktopPane3.setBounds(0, 470, 960, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(80, 30, 0, 2);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 0, 0, 120);

        etqTitulo3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etqTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        etqTitulo3.setText("MENU DOCTORES");
        getContentPane().add(etqTitulo3);
        etqTitulo3.setBounds(150, 80, 280, 80);

        etqTitulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etqTitulo1.setForeground(new java.awt.Color(8, 83, 148));
        etqTitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/stethoscope.png"))); // NOI18N
        etqTitulo1.setText("MENU DOCTORES");
        etqTitulo1.setFocusable(false);
        etqTitulo1.setOpaque(true);
        etqTitulo1.setRequestFocusEnabled(false);
        etqTitulo1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(etqTitulo1);
        etqTitulo1.setBounds(0, 20, 510, 450);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/fondoBlanco.jpg"))); // NOI18N
        jLabel7.setText("jLabel2");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-70, -30, 2598, 1690);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 0, 0, 2);
        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(10, 120, 300, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etqTitulo1;
    private javax.swing.JLabel etqTitulo3;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonKardex;
    private javax.swing.JButton jButtonKardex1;
    private javax.swing.JButton jButtoncContactos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
