package clinicamedicasolidarista.vista;

import java.util.Observable;
import java.util.Observer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Angelica
 */
public class vista2 extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form vista2
     */
    public vista2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        etqPrincipalUsuario = new javax.swing.JLabel();
        etqUsuario = new javax.swing.JLabel();
        etqContraseña = new javax.swing.JLabel();
        textRegistroUsuario = new javax.swing.JTextField();
        textContraseña = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        etqOlvidasteTuContraseña = new javax.swing.JLabel();
        etqFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqPrincipalUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/figura-de-usuario.png"))); // NOI18N
        panelPrincipal.add(etqPrincipalUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 130, 130));

        etqUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/1475740981_Username.png"))); // NOI18N
        panelPrincipal.add(etqUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        etqContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/1475740969_Password_2.png"))); // NOI18N
        panelPrincipal.add(etqContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        textRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRegistroUsuarioActionPerformed(evt);
            }
        });
        panelPrincipal.add(textRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 190, 30));
        panelPrincipal.add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 190, 30));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/login-button.png"))); // NOI18N
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        panelPrincipal.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 70, 40));

        etqOlvidasteTuContraseña.setForeground(new java.awt.Color(255, 255, 255));
        etqOlvidasteTuContraseña.setText("¿Olvidaste tu Contraseña?");
        panelPrincipal.add(etqOlvidasteTuContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        etqFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/fondo2.png"))); // NOI18N
        etqFondo.setText("jLabel1");
        panelPrincipal.add(etqFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 370, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRegistroUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRegistroUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel etqContraseña;
    private javax.swing.JLabel etqFondo;
    private javax.swing.JLabel etqOlvidasteTuContraseña;
    private javax.swing.JLabel etqPrincipalUsuario;
    private javax.swing.JLabel etqUsuario;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JTextField textRegistroUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
