/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicamedicasolidarista.vista;

import clinicamedicasolidarista.ClinicaMedicaSolidarista;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Angelica
 */
public class vistaRegistroMedico extends javax.swing.JFrame {

    /**
     * Creates new form vistaSolicitudCita
     */
    public vistaRegistroMedico() {
        initComponents();
        txtCedulaAyuda.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textNombreDoc = new javax.swing.JTextField();
        textSegundoApellidoDoc = new javax.swing.JTextField();
        textPrimerApellidoDoc = new javax.swing.JTextField();
        cmbIdentificacionDoc = new javax.swing.JComboBox<>();
        textIdentificacionDoc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        textCelularDoc = new javax.swing.JTextField();
        textNumHabitacionDoc = new javax.swing.JTextField();
        textCorreoDoc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        textFechaNacDoc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        horarioDoc = new javax.swing.JLabel();
        txtHoraDoc = new javax.swing.JPasswordField();
        textContraseñaDoc = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        textUsuarioDoc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textConfirmarContraseñaDoc1 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        txtDiaDoc = new javax.swing.JPasswordField();
        horariobtnDoc = new javax.swing.JButton();
        txtCedulaAyuda = new javax.swing.JTextField();
        txtFechaAyuda = new javax.swing.JTextField();
        tituloFormularioAdministradores = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnEnviarDoc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(962, 728));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(940, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACIÓN PERSONAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 573));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("NOMBRE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setText("PRIMER APELLIDO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel6.setText("SEGUNDO APELLIDO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jLabel7.setText("TIPO DE IDENTIFICACIÓN ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 99, -1, -1));

        jLabel8.setText("No DE IDENTIFICACIÓN ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        textNombreDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreDocActionPerformed(evt);
            }
        });
        textNombreDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNombreDocKeyTyped(evt);
            }
        });
        jPanel2.add(textNombreDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 160, -1));

        textSegundoApellidoDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSegundoApellidoDocKeyTyped(evt);
            }
        });
        jPanel2.add(textSegundoApellidoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 155, -1));

        textPrimerApellidoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrimerApellidoDocActionPerformed(evt);
            }
        });
        textPrimerApellidoDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPrimerApellidoDocKeyTyped(evt);
            }
        });
        jPanel2.add(textPrimerApellidoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 155, -1));

        cmbIdentificacionDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula de Identidad", "Cédula de Residencia", "Cédula de Refugiado", "Permiso de Estudio" }));
        cmbIdentificacionDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdentificacionDocActionPerformed(evt);
            }
        });
        jPanel2.add(cmbIdentificacionDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 131, -1));

        textIdentificacionDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textIdentificacionDocKeyTyped(evt);
            }
        });
        jPanel2.add(textIdentificacionDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 135, -1));

        jLabel16.setText("NUMERO DE TELÉFONO DE CONTACTO");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel17.setText("CELULAR");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel18.setText("CASA DE HABITACIÓN");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, 20));

        jLabel20.setText("CORREO ELECTRONICO");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        textCelularDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCelularDocActionPerformed(evt);
            }
        });
        textCelularDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCelularDocKeyTyped(evt);
            }
        });
        jPanel2.add(textCelularDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 160, -1));

        textNumHabitacionDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumHabitacionDocActionPerformed(evt);
            }
        });
        textNumHabitacionDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumHabitacionDocKeyTyped(evt);
            }
        });
        jPanel2.add(textNumHabitacionDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 160, -1));
        jPanel2.add(textCorreoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 280, -1));

        jLabel22.setText("FECHA DE NACIMIENTO");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        textFechaNacDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFechaNacDocKeyTyped(evt);
            }
        });
        jPanel2.add(textFechaNacDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 140, -1));

        jLabel9.setText("CONTRASEÑA");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        horarioDoc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        horarioDoc.setText("HORARIO ");
        jPanel2.add(horarioDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        txtHoraDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraDocActionPerformed(evt);
            }
        });
        jPanel2.add(txtHoraDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 180, -1));
        jPanel2.add(textContraseñaDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 180, -1));

        jLabel11.setText("NOMBRE DE USUARIO");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        textUsuarioDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textUsuarioDocKeyTyped(evt);
            }
        });
        jPanel2.add(textUsuarioDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 130, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 770, 200));

        jLabel12.setText("HORA");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, 20));

        jLabel13.setText("CONFIRMAR CONTRASEÑA");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        textConfirmarContraseñaDoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConfirmarContraseñaDoc1ActionPerformed(evt);
            }
        });
        jPanel2.add(textConfirmarContraseñaDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 180, -1));

        jLabel14.setText("DIA");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        txtDiaDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaDocActionPerformed(evt);
            }
        });
        jPanel2.add(txtDiaDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 180, -1));

        horariobtnDoc.setText("REGISTRAR HORARIO");
        jPanel2.add(horariobtnDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        txtCedulaAyuda.setEditable(false);
        txtCedulaAyuda.setBackground(new java.awt.Color(255, 255, 255));
        txtCedulaAyuda.setForeground(new java.awt.Color(128, 128, 128));
        txtCedulaAyuda.setText("Debe digitar cédula completa");
        txtCedulaAyuda.setBorder(null);
        txtCedulaAyuda.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtCedulaAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaAyudaActionPerformed(evt);
            }
        });
        jPanel2.add(txtCedulaAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 210, 20));

        txtFechaAyuda.setEditable(false);
        txtFechaAyuda.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaAyuda.setForeground(new java.awt.Color(128, 128, 128));
        txtFechaAyuda.setText("Formato: dd-mm-aaaa");
        txtFechaAyuda.setBorder(null);
        txtFechaAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaAyudaActionPerformed(evt);
            }
        });
        jPanel2.add(txtFechaAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 160, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 920, 580));

        tituloFormularioAdministradores.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tituloFormularioAdministradores.setText("FORMULARIO DE REGISTRO PARA  MEDICOS");
        jPanel1.add(tituloFormularioAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 430, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/asetaca.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnEnviarDoc.setText("ENVIAR FORMULARIO ");
        btnEnviarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarDocActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 820, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/log out.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicamedicasolidarista/imagenes/fondoBlanco.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 700));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPrimerApellidoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrimerApellidoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrimerApellidoDocActionPerformed

    private void textNombreDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreDocActionPerformed

    private void textCelularDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCelularDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCelularDocActionPerformed

    private void textNumHabitacionDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumHabitacionDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumHabitacionDocActionPerformed

    private void btnEnviarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarDocActionPerformed

    private void txtHoraDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraDocActionPerformed

    private void textConfirmarContraseñaDoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConfirmarContraseñaDoc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textConfirmarContraseñaDoc1ActionPerformed

    private void txtDiaDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaDocActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClinicaMedicaSolidarista.DOC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textNombreDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNombreDocKeyTyped
        char c = evt.getKeyChar();
       
       if(Character.isDigit(c)){
            textNombreDoc.setBorder(BORDER_ERROR);
            textNombreDoc.setToolTipText("Digite solo letras");
           evt.consume();
       }
       else{
            textNombreDoc.setBorder(BORDER_RIGHT);
            textNombreDoc.setToolTipText("");
       }
    }//GEN-LAST:event_textNombreDocKeyTyped

    private void textPrimerApellidoDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrimerApellidoDocKeyTyped
       char c = evt.getKeyChar();
       
       if(Character.isDigit(c)){
            textPrimerApellidoDoc.setBorder(BORDER_ERROR);
            textPrimerApellidoDoc.setToolTipText("Digite solo letras");
           evt.consume();
       }
       else{
            textPrimerApellidoDoc.setBorder(BORDER_RIGHT);
            textPrimerApellidoDoc.setToolTipText("");
       }
    }//GEN-LAST:event_textPrimerApellidoDocKeyTyped

    private void textSegundoApellidoDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSegundoApellidoDocKeyTyped
        char c = evt.getKeyChar();
       
       if(Character.isDigit(c)){
            textSegundoApellidoDoc.setBorder(BORDER_ERROR);
            textSegundoApellidoDoc.setToolTipText("Digite solo letras");
           evt.consume();
       }
       else{
            textSegundoApellidoDoc.setBorder(BORDER_RIGHT);
            textSegundoApellidoDoc.setToolTipText("");
       }
    }//GEN-LAST:event_textSegundoApellidoDocKeyTyped

    private void textIdentificacionDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIdentificacionDocKeyTyped
        char c = evt.getKeyChar();
       
       if(Character.isLetter(c)){
            textIdentificacionDoc.setBorder(BORDER_ERROR);
            textIdentificacionDoc.setToolTipText("Digite solo letras");
           evt.consume();
       }
       else{
            textIdentificacionDoc.setBorder(BORDER_RIGHT);
            textIdentificacionDoc.setToolTipText("");
       }
    }//GEN-LAST:event_textIdentificacionDocKeyTyped

    private void textFechaNacDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechaNacDocKeyTyped
        char c = evt.getKeyChar();
       
       if(Character.isLetter(c)){
            textFechaNacDoc.setBorder(BORDER_ERROR);
            textFechaNacDoc.setToolTipText("Digite solo letras");
           evt.consume();
       }
       else{
            textFechaNacDoc.setBorder(BORDER_RIGHT);
            textFechaNacDoc.setToolTipText("");
       }
    }//GEN-LAST:event_textFechaNacDocKeyTyped

    private void textCelularDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCelularDocKeyTyped
       char c = evt.getKeyChar();
       
       if(Character.isLetter(c)){
            textCelularDoc.setBorder(BORDER_ERROR);
            textCelularDoc.setToolTipText("Digite solo letras");
           evt.consume();
       }
       else{
            textCelularDoc.setBorder(BORDER_RIGHT);
            textCelularDoc.setToolTipText("");
       }
    }//GEN-LAST:event_textCelularDocKeyTyped

    private void textNumHabitacionDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumHabitacionDocKeyTyped
       char c = evt.getKeyChar();
       
       if(Character.isLetter(c)){
            textNumHabitacionDoc.setBorder(BORDER_ERROR);
            textNumHabitacionDoc.setToolTipText("Digite solo letras");
           evt.consume();
       }
       else{
            textNumHabitacionDoc.setBorder(BORDER_RIGHT);
            textNumHabitacionDoc.setToolTipText("");
       }
    }//GEN-LAST:event_textNumHabitacionDocKeyTyped

    private void textUsuarioDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textUsuarioDocKeyTyped
       char c = evt.getKeyChar();
       
       if(Character.isLetter(c)){
            textUsuarioDoc.setBorder(BORDER_ERROR);
            textUsuarioDoc.setToolTipText("Digite solo letras");
           evt.consume();
       }
       else{
            textUsuarioDoc.setBorder(BORDER_RIGHT);
            textUsuarioDoc.setToolTipText("");
       }
    }//GEN-LAST:event_textUsuarioDocKeyTyped

    private void txtCedulaAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaAyudaActionPerformed

    private void txtFechaAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaAyudaActionPerformed

    private void cmbIdentificacionDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdentificacionDocActionPerformed
        txtCedulaAyuda.setVisible(true);
    }//GEN-LAST:event_cmbIdentificacionDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaRegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaRegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaRegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaRegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaRegistroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarDoc;
    private javax.swing.JComboBox<String> cmbIdentificacionDoc;
    private javax.swing.JLabel horarioDoc;
    private javax.swing.JButton horariobtnDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textCelularDoc;
    private javax.swing.JPasswordField textConfirmarContraseñaDoc1;
    private javax.swing.JPasswordField textContraseñaDoc;
    private javax.swing.JTextField textCorreoDoc;
    private javax.swing.JTextField textFechaNacDoc;
    private javax.swing.JTextField textIdentificacionDoc;
    private javax.swing.JTextField textNombreDoc;
    private javax.swing.JTextField textNumHabitacionDoc;
    private javax.swing.JTextField textPrimerApellidoDoc;
    private javax.swing.JTextField textSegundoApellidoDoc;
    private javax.swing.JTextField textUsuarioDoc;
    private javax.swing.JLabel tituloFormularioAdministradores;
    private javax.swing.JTextField txtCedulaAyuda;
    private javax.swing.JPasswordField txtDiaDoc;
    private javax.swing.JTextField txtFechaAyuda;
    private javax.swing.JPasswordField txtHoraDoc;
    // End of variables declaration//GEN-END:variables
  public static Border BORDER_ERROR = BorderFactory.createLineBorder(Color.red);
     public static Border BORDER_RIGHT = BorderFactory.createLineBorder(Color.BLACK);

// arreglar la parte de la tabla en la base de datos y arreglar los modelos para que calcen con la base
    
}
